# Generated by Django 4.0.1 on 2022-01-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Folders',
            new_name='Folder',
        ),
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
