# Generated by Django 4.0.1 on 2022-01-15 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_documents_document_rename_folders_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topic',
            name='topics',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Islamic', 'Islamic'), ('Jazz', 'Jazz'), ('Entrepreneurship', 'Entrepreneurship'), ('Space', 'Space'), ('Poverty', 'Poverty')], default='Pop', max_length=50),
        ),
    ]
