# Generated by Django 4.0.1 on 2022-01-15 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_document_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(related_name='documents', to='apis.Topic'),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topics',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Islamic', 'Islamic'), ('Jazz', 'Jazz'), ('Entrepreneurship', 'Entrepreneurship'), ('Space', 'Space'), ('Poverty', 'Poverty'), ('SpekiLove!', 'Spekit')], default='Pop', max_length=50),
        ),
    ]
