# Generated by Django 4.0.1 on 2022-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_topic_name_document_topics_document_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='folder',
            new_name='folder_name',
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topics',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Islamic', 'Islamic'), ('Jazz', 'Jazz'), ('Entrepreneurship', 'Entrepreneurship'), ('Space', 'Space'), ('Poverty', 'Poverty'), ('SpekiLove!', 'Spekit')], default='Pop', max_length=50, unique=True),
        ),
    ]
