# Generated by Django 4.0.1 on 2022-01-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_rename_folder_document_folder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topics',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
