# Generated by Django 4.0.1 on 2022-01-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_topic_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='name',
            new_name='folder_name',
        ),
    ]
