# Generated by Django 4.0.1 on 2022-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_rename_name_folder_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
